version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - '1337:1337'
    environment:
      - SUPABASE_HOST=${SUPABASE_HOST}
      - SUPABASE_PORT=${SUPABASE_PORT}
      - SUPABASE_DB=${SUPABASE_DB}
      - SUPABASE_USER=${SUPABASE_USER}
      - SUPABASE_PASSWORD=${SUPABASE_PASSWORD}
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_KEY=${SUPABASE_KEY}
    depends_on:
      - supabase

  frontend:
    build: ./frontend
    ports:
      - '3000:5000'
    depends_on:
      - backend

  supabase:
    image: supabase/postgres
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_PASSWORD=${SUPABASE_PASSWORD}
      - POSTGRES_DB=${SUPABASE_DB}
      - POSTGRES_USER=${SUPABASE_USER}
    volumes:
      - supabase-data:/var/lib/postgresql/data

volumes:
  supabase-data:
